//
//  K.swift
//  Struyach Fitness
//
//  Created by Мария Межова on 20/2/23.
//

import Foundation
import UIKit


struct K {
    static let ecd = "ECD Plan"
    static let bodyweight = "Bodyweight"
    static let struyach = "Struyach Plan"
    static let pelvicPower = "Pelvic Power Plan"
    static let bellyBurner = "Belly Burner Plan"
    
    static var ecdDescription = "Transform your body with our ECD Plan - designed for gym or CrossFit box training. \n\nJoin today and start your fitness journey with us!"
    static var struyachDescription = "Take your training to the next level with our Struyach Plan - designed specifically for experienced athletes \n\nSubscribing to Struyach Plan also gives you a free access to the ECD Plan! Join now!"
    static var pelvicDescription = "Tone and strengthen your pelvic muscles with our 10 high-intensity workouts. \n\nJoin today for a stronger, healthier you!"
    static var bellyDescription = "Get rid of stubborn belly fat and achieve a leaner, fitter body with our 10 high-intensity workouts. \n\nJoin today!"
    
    static let shortPlanDescriptions = [
        "Get fit and toned with our Bodyweight Training Plan - no equipment needed, perfect for on-the-go workouts!".localized(),
        "Transform your body with our ECD Plan - designed for gym or CrossFit box training".localized(),
        "Take your training to the next level with our Struyach Plan - designed specifically for experienced athletes".localized(),
        "Tone and strengthen your pelvic muscles with our 10 high-intensity workouts".localized(), "Get rid of stubborn belly fat and achieve a leaner, fitter body with our 10 high-intensity workouts".localized()]
    
    static let appDescription = "Welcome to our cosy fitness app! \n\nWe understand that you want to achieve your fitness goals with a personalized touch, and that's exactly what we provide. Our app is not just another AI-generated workout plan - we believe in the power of experience and empathy. \n\nMeet Roman Mezhov, our experienced coach with over 12 years of coaching in various activities, including cycle, hot iron, cross-training, and more. With almost a decade of experience in creating training programs, Roman has crafted unique and effective plans that cater to your individual needs and abilities. \n\nIn this app, you will have access to three monthly subscription training plans and two lifetime plans that will change your fitness game forever. The best part? Your coach is always available to answer your questions and provide feedback on your technique. Our commenting feature also allows you to share your progress with the coach and other users, creating a supportive community that encourages you every step of the way. \n\nOur Bodyweight plan is perfect for those who are always on-the-go, providing you with quick and effective workouts that require no special equipment. This plan is completely free, so there's no excuse not to get started today. \n\nOur ECD plan is the main training program, suitable for both beginners and intermediate-level athletes. With a full range of movements using common gym equipment, this well-balanced program will never leave you bored. \n\nOur Stryuach plan is for advanced athletes who are serious about pushing their limits and achieving visible progress. This plan is designed for competitive athletes who are in it to win it.By subscribing to this plan, you'll also get an access to our ECD Plan. \n\nIn addition to these plans, we also offer two plans with ten high-intensity workouts each - Belly Burner and Pelvic Power. These plans are specifically designed to strengthen the muscles of the press and pelvic muscles, respectively. \n\nBut that's not all - our app also gives you free access to our coach's blog, where you can read his thoughts and insights on working out and doing business in the fitness industry. In the Profile section, you can keep track of your personal records in weightlifting movements and share them with other users. \n\nJoin our community and achieve your fitness goals with the help of our expert coach and personalized training plans. Start your fitness journey with us today!"
    
    static let privacyPolicy = "\nLast updated: 12-06-2023 \n\nThis Privacy Policy governs the manner in which Struyach Fitness Apps collects, uses, maintains, and discloses information collected from users (\"User\") of the Struyach Fitness Apps mobile applications (\"App\"). \n\nInformation We Collect \n1.1 Personal Information\nWe may collect the following personal information from Users: \n- Email and password: We require Users to create an account using their email and password to access certain features of the App. \n- Avatar images: The App allows Users to upload and store avatar images for their profiles. \n- Personal records in weightlifting: Users can input and store personal weightlifting records within the App. \n- Liked posts and workouts: The App may collect information about posts and workouts that Users have liked. \n- Comments and media: The App collects and stores any comments made by Users, including text, video, and photo media. \n- In-app purchases and subscriptions: The App tracks and records Users' in-app purchases and subscription details. \n\n1.2 Data Storage \nAll User data mentioned above is securely stored on servers hosted by Firebase and RevenueCat. We take appropriate measures to protect the data against unauthorized access, alteration, disclosure, or destruction. \n\nUse of Collected Information \n2.1 Personalization and Service Improvement \nThe collected information is used to provide personalized experiences, improve our services, and optimize the App's performance. This includes, but is not limited to, suggesting relevant content, tracking workout progress, and enhancing user interaction within the App. \n2.2 Notification Management \nUsers can manage their notification preferences within the App's settings. \n2.3 Email Privacy \nUsers have the option to hide their email from other users within the App. \n2.4 Subscriptions Management \nUsers can manage their subscriptions through the device settings. Additional terms regarding subscriptions are outlined in the Paywalls Terms of Use. \n\nData Sharing \n3.1 Third-Party Sharing \nWe do not share User data with third parties in any way, except as necessary to provide the App's services and as required by law enforcement agencies or applicable regulations. \n\nAccount Deletion \n4.1 Account Deactivation \nUsers can choose to permanently delete their accounts and all associated data from the App. This action is irreversible and cannot be undone. \n\nChanges to This Privacy Policy \nWe reserve the right to update this Privacy Policy at any time. If there are any changes to our Privacy Policy, Users will be shown a new version, and they must agree to it in order to continue using the app. \n\nContact Us \nIf you have any questions or concerns about this Privacy Policy or the App, please contact us at maria.mezhova@yahoo.com."
    
    static var accountDeleteMessage = "Deleting your account will permanently remove all your data and cannot be undone. This action is irreversible.\nBefore deleting your account, please consider the following:\n1. Data Loss: All your personal information, including profile details, messages, and preferences, will be deleted and cannot be recovered.\n2. Access Revocation: You will lose access to any associated services, features, or benefits linked to your account.\n3. Subscription Cancellation: If you have an active subscription, deleting your account will not cancel any active subscriptions tied to your account, you have to cancel them on your own in Settings -> Apple ID -> Subscriptions. \n4. Social Connections: Connections or interactions with other users, friends and coach may be lost. You will no longer be able to communicate with them through the platform.\nPlease take your time to consider this decision carefully. If you have any concerns or questions, we recommend you to send a message to the developer for assistance before proceeding.\nTo confirm the deletion of your account and proceed, tap \"Delete Account\". To cancel and retain your account, tap \"Cancel\"."
}

